### PR TITLE
Add start screen to game

### PR DESCRIPTION
**Pull request by tomtomesteves**
The games begins after opening and sometimes the player could just want to wait some time to start it. Don't know if you guys want that but think is a good idea to have a start screen. Looking to improve some other things like pause menu and volume control. 
One little question: The `hacktoberfest-accepted` tag can be added to the pr ? Would appreciate that.

### CODE REVIEW

**Comment by karate** [comment]
Hello and thank you for you contribution.
That's a great idea, but I see some problems:

- The player cannot quit while in the start screen, while in-game they can press `q`. Could you support this, and change the text accordingly.
- There is a help text (`instructions`) when the game begins ("Press SPACE to fire. Press 'q' to quit") that disappears after some time. If you stay in the start screen long enough, when the game starts you don't get to read the text. I'm not sure how to solve this.
- Also, please use SPACE to start the game, instead of UP key.

I'm adding the `hacktoberfest` label to the whole repo.

**Comment by tomtomesteves** [comment]
Great ideias, will work on it and update here!!

**Comment by tomtomesteves** [comment]
:recycle: @karate 
1. Created the option to close the game in start menu.
2. Display the controls in main menu, and removed it from beginning of the game.
3. Changed the key to start the game, from UP to SPACE as requested.

**Comment by karate** [comment]
Thanks @tomtomesteves, this is much better.

Now there's too much info in the start screen. I think the control instructions are better displayed when the game begins, along with the small delay that gives the player time to familiarize. When I said " I'm not sure how to solve this" I meant how to solve the problem with the text disappearing too soon. Could you revert that, and just make sure that the `instructions` texts stays visible for a fixed amount of time (until the first enemies appear)?

**Comment by tomtomesteves** [comment]
:recycle: @karate 
To solve that, after the player leaves start screen i just incrementes the UPDATE_INTERVAL with the actual tick. Now, the time the player stays in the start screen will not change the initial time to start the game with the instruction on top.

**Comment by tomtomesteves** [comment]
> The player's plane is being created just a few lines above from an existing Sprite png.
> I don't think we need to create it again, and definitely no need to duplicate the png file.
> 
> Also, the variable name `carImg` doesn't look relevant.
> 
> Edit: Just to be clear, I'm referring to line 54 of `ff.py`

You want me to remove the plane from start screen ?

**Comment by karate** [comment]
Either remove the plane, or, if you prefer to keep it, use the existing Sprite.
Either way, please remove the new `player_simple.png` file

**Comment by tomtomesteves** [comment]
:recycle:

**Comment by karate** [comment]
This is great. Thank you!

**Pull request merged**
