### PR TITLE
SFX: Added Mixer class and some music/sounds

### PR DESCRIPTION
**Pull request by Alfro**
The sfx files can be changed. These are just for example
**Background Music:** Space Rhythm 2 by Secret Circuit
http://freemusicarchive.org/music/Secret_Circuit/Bonus_Beat_Blast_2011/66_secret_circuit-space_rhythm_2

**Bullets:** Cut from here:
https://freesound.org/people/DamianMinnie/sounds/327553/

**Explosions:** Variations over this:
https://freesound.org/people/V-ktor/sounds/435415/

Note: All sfx seems to be CC licenses. Attribution should be added somewhere.

### CODE REVIEW

**Comment by karate** [comment]
This is great @Alfro! Do you think you could keep the background music files a little bit smaller? Maybe loop a small 20" audio

**Comment by karate** [comment]
Also, we want the explosion sound when the ship crashes with an enemy plane as well.

**Comment by Alfro** [comment]
Whops! I found this sitting on my projects folder, so I decided to change those couple of things :P 
 Hope you like it!

**Comment by karate** [comment]
Thanks @Alfro.
Could you also add the explosion sound when the player ship gets destroyed by bullet damage?
It's a few lines after your current commit.

**Comment by Alfro** [comment]
There you go

**Comment by karate** [comment]
Thank you!!

**Pull request merged**
